version: "3.7"
services:
  app:
    build:
      args:
        user: ${APP_USERNAME}
        uid: 1000
        cron: ${MAIL_BACKUP_TIME}
        appname: ${APP_NAME}
        LANG: ${LANG}
        LANGUAGE: ${LANGUAGE}
        TZ: ${TZ}
      context: ./
      dockerfile: Dockerfile
    image: laravel-${APP_NAME}
    container_name: laravel-${APP_NAME}
    hostname: ${APP_NAME}
    ports:
      - ${APP_PORT}:8000
    restart: unless-stopped
    working_dir: /var/www/${APP_NAME}
    volumes:
      - /opt/krankmeldung/backups:/var/www/${APP_NAME}/storage/backups
    networks:
      - proxy
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: laravel-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /opt/krankmeldung/mysql:/var/lib/mysql
    networks:
      - proxy
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - /opt/krankmeldung/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - proxy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel-phpmyadmin
    ports:
      - ${DB_MYADMIN_PORT}:80
    networks:
      - proxy
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
networks:
  proxy:
    driver: bridge
